name: CI Pipeline

on:
  push:
    branches: [main]  # Triggers when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for building

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Get your code from GitHub

    - name: Build Docker image
      run: docker build -t my-app .  # Build your Docker image from the Dockerfile
